### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by GosroPoorheydar** [BVictorB/functional-programming#1]
Net bestand. Duidelijk wat je voor ogen hebt. 

Ik mis alleen wat je verwachtingen zijn.

Bijvoorbeeld: 

Denk je dat stijging van prijzen positief of negatief wordt beinvloedt door het
openen van niewe parkeergarages?

Je hoofdvraag is goed gestructureerd en defineerbaar, maar sommige deelvragen 
nog niet helemaal.

"Is the accessibility for disabled people good in all parking garages in Amsterdam?"

Wat is good? Good is niet makelijk te kwantificeren. 

Mischien "Capable of servicing all disabled drivers in amsterdam"?

je hebt al een helder idee van welke data je nodig hebt, dus ik heb daar geen commentaar op
goed bezig.

**Comment by BVictorB** [comment]
Thanks voor de feedback, is verwerkt in mijn wiki/readme!
