### ISSUE TITLE
Feedback repo

### ISSUE THREAD

**Issue by sreen020** [BVictorB/functional-programming#3]
Met Victor heb ik besproken om nu alleen zijn code te reviewen en later vandaag of morgen de rest.

De volgende feedback punten gaan over: 
https://github.com/BVictorB/functional-programming/wiki/Functional-programming-code

- Je gebruikt in je getData('heleLangeLink.json'). Misschien is het netter om een const aan te maken waar deze endpoint instaat.

- (meer een vraag dan feedback) Je maakt in filterDataFromKey en getData gebruik van een .map, is een foreach niet netter?

- die const colors heb je netjes en overzichtelijk neergezet!

- checkContrast, Ik snap niet zo goed wat je hier doet, misschien zo even in een call uitleggen

Verder nice en clean code, goed gebruik gemaakt van comments en netjes gedocumenteerd in je wiki.

Ik ben trots op je Victor!

**Comment by BVictorB** [comment]
Thanks voor de feedback, ik ga er naar kijken!
